// app/layout.tsx 파일

import type { Metadata } from 'next';
import { createClientForServer } from '@/utils/supabase/server';
import Sidebar from '@/component/Sidebar';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  const supabase = await createClientForServer();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  const userInfo = user?.user_metadata;
  console.log(userInfo);

  // console.log('RootLayout userInfo');
  // console.log(userInfo);

  return (
    <html lang="en">
      <body className={`antialiased h-screen flex items-center justify-between`}>
        {userInfo && <Sidebar userInfo={userInfo}></Sidebar>}
        {children}
      </body>
    </html>
  );
}
